# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

default_platform(:ios)

platform :ios do
  # A helper lane for refreshing provisioning profiles.
  lane :refresh_profiles do
    match(type: "development", force: true)
    # match(type: "appstore")
  end

  lane :beta do
    # increment_build_number

    build_app(scheme: "Cardin",
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "com.Cardin" => "com.Cardin Ad Hoc"
        }
      }
    )
    
    deploygate(
      api_token: "e5f0500fbdffb28f47e773115573e61ad6601ccb",
      user: "cardin",
      message: "Build #{lane_context[SharedValues::BUILD_NUMBER]}"
    )
  end
end
